### ISSUE TITLE
Also load translations from assets

### ISSUE THREAD

**Issue by arthurbambou** [arthurbambou/Server-Translations#9]
Currently Server-Translations only loads translations files in datapacks, the issue with this is that other mods that are not only server side won't have their translations files loaded.
The datapack system should be kept but a asset should run in parallel when mods which run on both client and server sides are present.

Issues that can't be fixed with Server-Translations until this is closed:
[Fabric<->Discord-Link#136](https://github.com/arthurbambou/Fabric---Discord-Link/issues/136)

**Comment by supersaiyansubtlety** [comment]
afaict translations are no longer loaded from assets in 1.4.16.

Is that intentional?

**Comment by arthurbambou** [comment]
This was never fixed.
